[pytest]
markers =
    login: Login tests
    smoke: Smoke tests
    regression: Regression tests
    forgot password: Forgot Password tests
    leave: Leave Management tests
    claim: Claim Module Test Cases